name = "meme-replicator"
main = "src/worker.js"
compatibility_date = "2024-01-01"

[[d1_databases]]
binding = "DB"
database_name = "meme-replicator"
database_id = "289daca3-fc68-4823-9685-3f6d255c1b1d"


[vars]
SITE_URL = "https://meme-replicator.oliverpartridge.workers.dev/"
AUTH0_DOMAIN = "dev-xluvqyrnc6lhmal6.us.auth0.com"
AUTH0_CLIENT_ID = "LClYgO5vAbC8sbXFoZsgJoMbkxICiyA3"

# Set these secrets:
# wrangler secret put AUTH0_CLIENT_SECRET
# 
# Auth0 Configuration: https://manage.auth0.com
# Enable: Passwordless > Email